# Generated by Django 4.1.2 on 2022-11-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=200)),
                ('resposta', models.CharField(max_length=100)),
                ('alternativa1', models.CharField(blank=True, max_length=100)),
                ('alternativa2', models.CharField(blank=True, max_length=100)),
                ('alternativa3', models.CharField(blank=True, max_length=100)),
                ('alternativa4', models.CharField(blank=True, max_length=100)),
                ('alternativa5', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
