# Generated by Django 4.1.2 on 2022-10-17 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receita',
            new_name='Pergunta',
        ),
    ]
