# Generated by Django 4.1.2 on 2022-10-29 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0002_rename_receita_pergunta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='alternativas',
        ),
        migrations.CreateModel(
            name='Alternativas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa1', models.CharField(blank=True, max_length=100)),
                ('alternativa2', models.CharField(blank=True, max_length=100)),
                ('alternativa3', models.CharField(blank=True, max_length=100)),
                ('alternativa4', models.CharField(blank=True, max_length=100)),
                ('alternativa5', models.CharField(blank=True, max_length=100)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perguntas.pergunta')),
            ],
        ),
    ]
