# Generated by Django 4.1.2 on 2022-10-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0004_rename_alternativas_alternativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='alternativa1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='alternativa2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='alternativa3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='alternativa4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='alternativa5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Alternativa',
        ),
    ]
