# Generated by Django 4.1.2 on 2022-11-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0006_auto_20221030_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
