# Generated by Django 4.1.2 on 2022-11-04 16:06

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perguntas', '0008_rankingpergunta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankingpergunta',
            name='id',
        ),
        migrations.AlterField(
            model_name='rankingpergunta',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=django.contrib.auth.models.User, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
