# Generated by Django 4.1.2 on 2022-11-05 02:19

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0002_alter_ranking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='pontos_rpg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=django.contrib.auth.models.User, related_name='ranking', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
